.TH SSLSNIFF 1
.SH NAME
sslsniff \- Monitoring a zobrazení informací o SSL spojení
.SH SYNOPSIS
.B sslsniff
[\fB\-r\fR \fI<file>\fR]
[\fB\-i\fR \fIinterface\fR]
[\fB\-h\fR]

.SH DESCRIPTION
Monitoring SSL spojení do předmětu Síťové aplikace a správa sítí, který zpracuje pcap soubor nebo zachytává spojení na síťovém rozhraní a zobrazí informace o SSL spojení.

.SH OPTIONS
.TP
\fB\-h ", " \-\-help\fR 
Zobrazení nápovědy.
.TP
\fB\-r <file>\fR
Soubor se síťovým provozem.
.TP
\fB\-i interface\fR
Zařízení, na kterém se má zachytávat síťový provoz. 
V případě chybějícího rozhraní se vypíše seznam rozhraní.
